export interface Category {
  id: string;
  slug: string;
  nameDe: string;
  nameEn: string;
  iconName: string;
  colorBg: string;
  colorText: string;
  colorBorder: string;
  badgeDe?: string;
  badgeEn?: string;
  subcategoriesDe: string[];
  subcategoriesEn: string[];
}

export const CATEGORIES: Category[] = [
  {
    id: 'fahrzeuge',
    slug: 'fahrzeugwelt',
    nameDe: 'Fahrzeuge',
    nameEn: 'Vehicles',
    iconName: 'Car',
    colorBg: 'bg-emerald-50 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white',
    colorText: 'text-emerald-700',
    colorBorder: 'hover:border-emerald-500',
    badgeDe: 'Top-Markt',
    badgeEn: 'Popular',
    subcategoriesDe: ['Autos', 'Motorräder & Roller', 'E-Bikes & Fahrräder', 'Wohnmobile & Caravans', 'Nutzfahrzeuge & LKW', 'Auto-Teile & Zubehör'],
    subcategoriesEn: ['Cars', 'Motorcycles & Scooters', 'E-Bikes & Bicycles', 'Camper Vans', 'Commercial Vehicles', 'Auto Parts & Accessories'],
  },
  {
    id: 'immobilien',
    slug: 'immobilien',
    nameDe: 'Immobilien',
    nameEn: 'Real Estate',
    iconName: 'Home',
    colorBg: 'bg-amber-50 text-amber-600 group-hover:bg-amber-600 group-hover:text-white',
    colorText: 'text-amber-700',
    colorBorder: 'hover:border-amber-500',
    badgeDe: 'Provisionsfrei',
    badgeEn: 'Direct',
    subcategoriesDe: ['Mietwohnungen', 'Eigentumswohnungen', 'Häuser zum Kauf', 'Häuser zur Miete', 'WG-Zimmer', 'Garagen & Stellplätze', 'Gewerbeimmobilien'],
    subcategoriesEn: ['Apartments for Rent', 'Condos for Sale', 'Houses for Sale', 'Houses for Rent', 'Shared Rooms (WG)', 'Garages & Parking', 'Commercial'],
  },
  {
    id: 'technik',
    slug: 'elektronik',
    nameDe: 'Technik & Elektronik',
    nameEn: 'Tech & Electronics',
    iconName: 'Smartphone',
    colorBg: 'bg-blue-50 text-blue-600 group-hover:bg-blue-600 group-hover:text-white',
    colorText: 'text-blue-700',
    colorBorder: 'hover:border-blue-500',
    badgeDe: 'Neuheiten',
    badgeEn: 'Gadgets',
    subcategoriesDe: ['Smartphones & Zubehör', 'Apple & iPhones', 'PCs & Notebooks', 'Tablets & E-Reader', 'TV, Video & Audio', 'Foto & Kamera', 'Smart Home'],
    subcategoriesEn: ['Smartphones & Accessories', 'Apple & iPhones', 'PCs & Laptops', 'Tablets & E-Readers', 'TV, Video & Audio', 'Cameras & Photo', 'Smart Home'],
  },
  {
    id: 'gaming',
    slug: 'gaming',
    nameDe: 'Gaming & Konsolen',
    nameEn: 'Gaming & Consoles',
    iconName: 'Gamepad2',
    colorBg: 'bg-indigo-50 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white',
    colorText: 'text-indigo-700',
    colorBorder: 'hover:border-indigo-500',
    badgeDe: 'PlayStation & PC',
    badgeEn: 'Gaming',
    subcategoriesDe: ['PlayStation 5 & 4', 'Xbox Series & One', 'Nintendo Switch & Retro', 'Gaming PCs & Zubehör', 'Videospiele', 'VR-Brillen'],
    subcategoriesEn: ['PlayStation 5 & 4', 'Xbox Series & One', 'Nintendo Switch & Retro', 'Gaming PCs & Gear', 'Video Games', 'VR Headsets'],
  },
  {
    id: 'haus-garten',
    slug: 'haus-garten',
    nameDe: 'Haus & Garten',
    nameEn: 'Home & Garden',
    iconName: 'Wrench',
    colorBg: 'bg-teal-50 text-teal-600 group-hover:bg-teal-600 group-hover:text-white',
    colorText: 'text-teal-700',
    colorBorder: 'hover:border-teal-500',
    subcategoriesDe: ['Möbel & Wohnen', 'Küche & Esszimmer', 'Schlafzimmer & Betten', 'Gartenmöbel & Pflanzen', 'Heimwerker & Werkzeug', 'Lampen & Licht'],
    subcategoriesEn: ['Furniture & Living', 'Kitchen & Dining', 'Bedrooms & Beds', 'Garden Furniture & Plants', 'DIY & Tools', 'Lighting & Lamps'],
  },
  {
    id: 'mode',
    slug: 'mode-beauty',
    nameDe: 'Mode & Accessoires',
    nameEn: 'Fashion & Accessories',
    iconName: 'ShoppingBag',
    colorBg: 'bg-rose-50 text-rose-600 group-hover:bg-rose-600 group-hover:text-white',
    colorText: 'text-rose-700',
    colorBorder: 'hover:border-rose-500',
    badgeDe: 'Trends',
    badgeEn: 'Trends',
    subcategoriesDe: ['Damenbekleidung', 'Herrenbekleidung', 'Damenschuhe', 'Herrenschuhe', 'Uhren & Schmuck', 'Taschen & Rucksäcke', 'Beauty & Parfüm'],
    subcategoriesEn: ['Womenswear', 'Menswear', 'Women Shoes', 'Men Shoes', 'Watches & Jewelry', 'Bags & Backpacks', 'Beauty & Fragrances'],
  },
  {
    id: 'baby-kind',
    slug: 'baby-kind',
    nameDe: 'Baby, Kind & Familie',
    nameEn: 'Baby, Kids & Family',
    iconName: 'Heart',
    colorBg: 'bg-purple-50 text-purple-600 group-hover:bg-purple-600 group-hover:text-white',
    colorText: 'text-purple-700',
    colorBorder: 'hover:border-purple-500',
    subcategoriesDe: ['Babykleidung & Schuhe', 'Kinderkleidung', 'Kinderwagen & Buggys', 'Autositze', 'Spielzeug & LEGO', 'Kindermöbel & Betten'],
    subcategoriesEn: ['Baby Clothing & Shoes', 'Kids Clothing', 'Strollers & Buggies', 'Car Seats', 'Toys & LEGO', 'Kids Furniture & Cribs'],
  },
  {
    id: 'sport-freizeit',
    slug: 'sport-freizeit',
    nameDe: 'Sport & Outdoor',
    nameEn: 'Sport & Outdoor',
    iconName: 'Bike',
    colorBg: 'bg-orange-50 text-orange-600 group-hover:bg-orange-600 group-hover:text-white',
    colorText: 'text-orange-700',
    colorBorder: 'hover:border-orange-500',
    subcategoriesDe: ['Fahrräder & Zubehör', 'Fitness & Gewichte', 'Camping & Outdoor', 'Wintersport & Ski', 'Wassersport', 'Ballsport & Teamsport'],
    subcategoriesEn: ['Bicycles & Gear', 'Fitness & Weights', 'Camping & Outdoors', 'Winter Sports & Ski', 'Water Sports', 'Team Sports'],
  },
  {
    id: 'buecher-musik',
    slug: 'buecher-musik',
    nameDe: 'Musik, Filme & Bücher',
    nameEn: 'Music, Movies & Books',
    iconName: 'BookOpen',
    colorBg: 'bg-sky-50 text-sky-600 group-hover:bg-sky-600 group-hover:text-white',
    colorText: 'text-sky-700',
    colorBorder: 'hover:border-sky-500',
    subcategoriesDe: ['Bücher, Romane & Fachliteratur', 'Comics & Mangas', 'Musikinstrumente & Audio', 'Schallplatten & Vinyl', 'Filme, DVDs & Blu-rays'],
    subcategoriesEn: ['Books & Literature', 'Comics & Manga', 'Musical Instruments', 'Vinyl Records & CDs', 'Movies & Blu-rays'],
  },
  {
    id: 'haustiere',
    slug: 'haustiere',
    nameDe: 'Haustiere & Zubehör',
    nameEn: 'Pets & Supplies',
    iconName: 'Dog',
    colorBg: 'bg-yellow-50 text-yellow-700 group-hover:bg-yellow-600 group-hover:text-white',
    colorText: 'text-yellow-800',
    colorBorder: 'hover:border-yellow-500',
    subcategoriesDe: ['Hunde & Welpen', 'Katzen & Kätzchen', 'Aquaristik & Fische', 'Kleintiere & Nager', 'Pferde & Reitsport', 'Kratzbäume & Zubehör'],
    subcategoriesEn: ['Dogs & Puppies', 'Cats & Kittens', 'Aquariums & Fish', 'Small Pets & Rodents', 'Horses & Riding', 'Supplies & Food'],
  },
  {
    id: 'jobs',
    slug: 'jobs-karriere',
    nameDe: 'Jobs & Karriere',
    nameEn: 'Jobs & Careers',
    iconName: 'Briefcase',
    colorBg: 'bg-emerald-50 text-emerald-700 group-hover:bg-emerald-700 group-hover:text-white',
    colorText: 'text-emerald-800',
    colorBorder: 'hover:border-emerald-600',
    badgeDe: 'Stellenangebote',
    badgeEn: 'Hiring',
    subcategoriesDe: ['Vollzeit & Teilzeit', 'Minijobs & Nebenjobs', 'Homeoffice & Remote', 'Studentenjobs & Praktika', 'Ausbildung & Handwerk'],
    subcategoriesEn: ['Full-time & Part-time', 'Mini Jobs & Side Jobs', 'Remote & Home Office', 'Student Jobs & Internships', 'Apprenticeships'],
  },
  {
    id: 'dienstleistungen',
    slug: 'dienstleistungen',
    nameDe: 'Dienstleistungen & Handwerk',
    nameEn: 'Services & Crafts',
    iconName: 'Hammer',
    colorBg: 'bg-slate-50 text-slate-700 group-hover:bg-slate-700 group-hover:text-white',
    colorText: 'text-slate-800',
    colorBorder: 'hover:border-slate-500',
    subcategoriesDe: ['Handwerker & Sanierung', 'Umzug, Transport & Entrümpelung', 'Reinigung & Haushaltshilfe', 'Nachhilfe & Unterricht', 'IT, Web & Grafikdesign'],
    subcategoriesEn: ['Craftsmen & Renovation', 'Moving & Transport', 'Cleaning Services', 'Tutoring & Classes', 'IT, Web & Design'],
  },
  {
    id: 'verschenken',
    slug: 'verschenken-tauschen',
    nameDe: 'Zu verschenken & Tauschen',
    nameEn: 'Free & Swap',
    iconName: 'Gift',
    colorBg: 'bg-pink-50 text-pink-600 group-hover:bg-pink-600 group-hover:text-white',
    colorText: 'text-pink-700',
    colorBorder: 'hover:border-pink-500',
    badgeDe: '100% Gratis',
    badgeEn: 'Free',
    subcategoriesDe: ['Kostenlos zum Abholen', 'Möbel zu verschenken', 'Kleidung zu verschenken', 'Elektronik zu verschenken', 'Tauschangebote'],
    subcategoriesEn: ['Free for Pick-up', 'Free Furniture', 'Free Clothing', 'Free Electronics', 'Swap Offers'],
  },
];
