import { Listing } from './mockData';

/**
 * KleinDeal.de Demo Sellers (Fictional Mock Data Only)
 * Used strictly for platform demonstration when Demo Mode is enabled.
 */
export const DEMO_SELLERS = {
  daniel: {
    id: 'seller-1',
    name: 'Daniel K.',
    trustScore: 98,
    memberSince: 'März 2022',
    verified: true,
    sellerType: 'Privat' as const,
    emailVerified: true,
    phoneVerified: true,
    identityVerified: false,
  },
  laura: {
    id: 'seller-2',
    name: 'Laura M.',
    trustScore: 95,
    memberSince: 'Januar 2023',
    verified: true,
    sellerType: 'Privat' as const,
    emailVerified: true,
    phoneVerified: false,
    identityVerified: false,
  },
  jonas: {
    id: 'seller-3',
    name: 'Jonas H.',
    trustScore: 100,
    memberSince: 'November 2021',
    verified: true,
    sellerType: 'Privat' as const,
    emailVerified: true,
    phoneVerified: true,
    identityVerified: true,
  },
  sophie: {
    id: 'seller-4',
    name: 'Sophie R.',
    trustScore: 96,
    memberSince: 'August 2022',
    verified: true,
    sellerType: 'Privat' as const,
    emailVerified: true,
    phoneVerified: true,
    identityVerified: false,
  },
  markus: {
    id: 'seller-5',
    name: 'Markus B.',
    trustScore: 92,
    memberSince: 'Februar 2023',
    verified: false,
    sellerType: 'Privat' as const,
    emailVerified: true,
    phoneVerified: false,
    identityVerified: false,
  },
  elena: {
    id: 'seller-6',
    name: 'Elena W.',
    trustScore: 99,
    memberSince: 'Mai 2020',
    verified: true,
    sellerType: 'Privat' as const,
    emailVerified: true,
    phoneVerified: true,
    identityVerified: true,
  },
  autozentrum: {
    id: 'seller-7',
    name: 'Autozentrum Süd',
    trustScore: 99,
    memberSince: 'Juni 2019',
    verified: true,
    sellerType: 'Gewerblich' as const,
    emailVerified: true,
    phoneVerified: true,
    identityVerified: true,
  },
  hausGarten: {
    id: 'seller-8',
    name: 'Haus & Garten Service Karlsruhe',
    trustScore: 97,
    memberSince: 'April 2021',
    verified: true,
    sellerType: 'Gewerblich' as const,
    emailVerified: true,
    phoneVerified: true,
    identityVerified: true,
  },
};

/**
 * 24 Realistic Demo Listings for KleinDeal.de
 * Stored strictly in memory, never written to production database or sitemaps.
 * Contains general city and postal codes only (no private addresses or exact coordinates).
 */
export const DEMO_LISTINGS: Listing[] = [
  // --- Fahrzeuge ---
  {
    id: 'demo-1',
    isDemo: true,
    slug: 'volkswagen-golf-7-1-6-tdi-karlsruhe',
    title: 'Volkswagen Golf 7 1.6 TDI',
    categorySlug: 'fahrzeugwelt',
    categoryNameDe: 'Fahrzeuge',
    categoryNameEn: 'Vehicles',
    subcategory: 'Autos',
    price: 9850,
    previousPrice: 10400,
    priceType: 'negotiable',
    locationCity: 'Karlsruhe',
    locationPlz: '76133',
    distanceKm: 2,
    postedDate: 'Heute, 11:30',
    condition: 'Gebraucht',
    descriptionDe: 'Gepflegter VW Golf 7 mit sparsamem 1.6 TDI Dieselmotor. Scheckheftgepflegt bei Volkswagen, TÜV bis 08/2025. Das Fahrzeug ist unfallfrei und hat Allwetterreifen auf Alufelgen.',
    descriptionEn: 'Well-maintained VW Golf 7 with economical 1.6 TDI engine. Full service history, MOT valid until 08/2025. Accident-free with all-season tires on alloy wheels.',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 142,
    favoriteCount: 18,
    seller: DEMO_SELLERS.autozentrum,
  },
  {
    id: 'demo-2',
    isDemo: true,
    slug: 'bmw-320d-touring-automatik-stuttgart',
    title: 'BMW 320d Touring Automatik',
    categorySlug: 'fahrzeugwelt',
    categoryNameDe: 'Fahrzeuge',
    categoryNameEn: 'Vehicles',
    subcategory: 'Autos',
    price: 14900,
    priceType: 'fixed',
    locationCity: 'Stuttgart',
    locationPlz: '70173',
    distanceKm: 45,
    postedDate: 'Gestern, 16:45',
    condition: 'Gebraucht',
    descriptionDe: 'BMW 320d M Sportpaket mit 8-Gang Steptronic Automatikgetriebe. Panorama-Glasdach, Head-Up Display und M-Sportfahrwerk. Bremsen und Inspektion neu durchgeführt.',
    descriptionEn: 'BMW 320d M Sport package with 8-speed Steptronic transmission. Panoramic sunroof, head-up display, and M sport suspension. Brakes and service recently renewed.',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80'],
    hasVideo: true,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hand-holding-a-smartphone-with-green-screen-41544-large.mp4',
    deliveryOptions: 'Abholung & Überführung',
    shippingAvailable: false,
    views: 289,
    favoriteCount: 34,
    seller: DEMO_SELLERS.jonas,
  },
  {
    id: 'demo-3',
    isDemo: true,
    slug: 'vespa-primavera-125-mannheim',
    title: 'Vespa Primavera 125',
    categorySlug: 'fahrzeugwelt',
    categoryNameDe: 'Fahrzeuge',
    categoryNameEn: 'Vehicles',
    subcategory: 'Motorräder & Roller',
    price: 3450,
    priceType: 'negotiable',
    locationCity: 'Mannheim',
    locationPlz: '68159',
    distanceKm: 30,
    postedDate: 'Vor 2 Tagen',
    condition: 'Wie neu',
    descriptionDe: 'Wunderschöne Vespa Primavera 125 in Verde Relax. Garagenfahrzeug mit nur 2.400 km Laufleistung. Inklusive Original Vespa Windschild und klappbarem Gepäckträger.',
    descriptionEn: 'Beautiful Vespa Primavera 125 in Verde Relax color. Garage kept with only 2,400 km. Includes original Vespa windshield and folding luggage rack.',
    images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 98,
    favoriteCount: 12,
    seller: DEMO_SELLERS.sophie,
  },

  // --- Immobilien ---
  {
    id: 'demo-4',
    isDemo: true,
    slug: 'helle-2-zimmer-wohnung-mit-balkon-karlsruhe',
    title: 'Helle 2-Zimmer-Wohnung mit Balkon',
    categorySlug: 'immobilien',
    categoryNameDe: 'Immobilien',
    categoryNameEn: 'Real Estate',
    subcategory: 'Mietwohnungen',
    price: 890,
    priceType: 'fixed',
    locationCity: 'Karlsruhe',
    locationPlz: '76137',
    distanceKm: 3,
    postedDate: 'Heute, 09:15',
    condition: 'Wie neu',
    descriptionDe: 'Renovierte 2-Zimmer-Wohnung mit 58 m² Wohnfläche in ruhiger Lage der Südstadt. Einbauküche vorhanden, sonniger Südbalkon und Aufzug im Gebäude. Kaltmiete 890 € zzgl. Nebenkosten.',
    descriptionEn: 'Renovated 2-room apartment with 58 m² living space in quiet location. Fitted kitchen, sunny south balcony, and elevator in the building. Cold rent 890 € plus utilities.',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Besichtigung vor Ort',
    shippingAvailable: false,
    views: 412,
    favoriteCount: 56,
    seller: DEMO_SELLERS.elena,
  },
  {
    id: 'demo-5',
    isDemo: true,
    slug: 'garage-in-zentraler-lage-ettlingen',
    title: 'Garage in zentraler Lage',
    categorySlug: 'immobilien',
    categoryNameDe: 'Immobilien',
    categoryNameEn: 'Real Estate',
    subcategory: 'Garagen & Stellplätze',
    price: 95,
    priceType: 'fixed',
    locationCity: 'Ettlingen',
    locationPlz: '76275',
    distanceKm: 8,
    postedDate: 'Gestern, 14:10',
    condition: 'Gebraucht',
    descriptionDe: 'Trockene Einzelgarage in einem geschützten Innenhof ab sofort zu vermieten. Mit Schwenktor, eigener Beleuchtung und Stromanschluss. Monatliche Miete 95 €.',
    descriptionEn: 'Dry single garage in a secured courtyard available for rent immediately. Equipped with swing gate, lighting, and power socket. Monthly rent 95 €.',
    images: ['https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Schlüsselübergabe vor Ort',
    shippingAvailable: false,
    views: 87,
    favoriteCount: 9,
    seller: DEMO_SELLERS.markus,
  },
  {
    id: 'demo-6',
    isDemo: true,
    slug: 'modernes-wg-zimmer-moebliert-heidelberg',
    title: 'Modernes WG-Zimmer, möbliert',
    categorySlug: 'immobilien',
    categoryNameDe: 'Immobilien',
    categoryNameEn: 'Real Estate',
    subcategory: 'WG-Zimmer',
    price: 520,
    priceType: 'fixed',
    locationCity: 'Heidelberg',
    locationPlz: '69115',
    distanceKm: 25,
    postedDate: 'Vor 3 Tagen',
    condition: 'Neu',
    descriptionDe: 'Voll möbliertes 18 m² Zimmer in einer entspannten 3er-WG in Heidelberg-Weststadt. Warmmiete inklusive Highspeed-WLAN, Waschmaschine und Geschirrspüler.',
    descriptionEn: 'Fully furnished 18 m² room in a friendly 3-person flatshare in Heidelberg Weststadt. Warm rent includes high-speed Wi-Fi, washing machine, and dishwasher.',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Besichtigung vor Ort',
    shippingAvailable: false,
    views: 310,
    favoriteCount: 42,
    seller: DEMO_SELLERS.laura,
  },

  // --- Technik & Elektronik ---
  {
    id: 'demo-7',
    isDemo: true,
    slug: 'apple-iphone-15-pro-256-gb-karlsruhe',
    title: 'Apple iPhone 15 Pro, 256 GB',
    categorySlug: 'elektronik',
    categoryNameDe: 'Technik & Elektronik',
    categoryNameEn: 'Tech & Electronics',
    subcategory: 'Smartphones & Tablets',
    price: 849,
    previousPrice: 890,
    priceType: 'negotiable',
    locationCity: 'Karlsruhe',
    locationPlz: '76131',
    distanceKm: 3,
    postedDate: 'Heute, 12:40',
    condition: 'Wie neu',
    descriptionDe: 'Apple iPhone 15 Pro mit 256 GB Speicher in Titan Natur. Das Smartphone befindet sich in einem erstklassigen Zustand ohne Gebrauchsspuren. Akkukapazität 97%, inklusive OVP.',
    descriptionEn: 'Apple iPhone 15 Pro with 256 GB storage in Natural Titanium. Excellent condition with no visible scratches. 97% battery capacity, includes original box.',
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80'],
    hasVideo: true,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hand-holding-a-smartphone-with-green-screen-41544-large.mp4',
    deliveryOptions: 'Abholung & Versand möglich',
    shippingAvailable: true,
    views: 245,
    favoriteCount: 31,
    seller: DEMO_SELLERS.daniel,
  },
  {
    id: 'demo-8',
    isDemo: true,
    slug: 'sony-playstation-5-mit-zwei-controllern-pforzheim',
    title: 'Sony PlayStation 5 mit zwei Controllern',
    categorySlug: 'elektronik',
    categoryNameDe: 'Technik & Elektronik',
    categoryNameEn: 'Tech & Electronics',
    subcategory: 'Gaming & Konsolen',
    price: 420,
    priceType: 'fixed',
    locationCity: 'Pforzheim',
    locationPlz: '75172',
    distanceKm: 22,
    postedDate: 'Heute, 10:15',
    condition: 'Wie neu',
    descriptionDe: 'PlayStation 5 Disc Edition in einwandfreiem Zustand. Im Lieferumfang enthalten sind zwei DualSense Wireless-Controller, HDMI 2.1 Kabel und die Originalverpackung.',
    descriptionEn: 'PlayStation 5 Disc Edition in perfect working condition. Comes with two DualSense wireless controllers, HDMI 2.1 cable, and original box.',
    images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Abholung bevorzugt',
    shippingAvailable: true,
    views: 189,
    favoriteCount: 22,
    seller: DEMO_SELLERS.jonas,
  },
  {
    id: 'demo-9',
    isDemo: true,
    slug: 'samsung-65-zoll-4k-smart-tv-bruchsal',
    title: 'Samsung 65 Zoll 4K Smart-TV',
    categorySlug: 'elektronik',
    categoryNameDe: 'Technik & Elektronik',
    categoryNameEn: 'Tech & Electronics',
    subcategory: 'TV & Audio',
    price: 590,
    priceType: 'negotiable',
    locationCity: 'Bruchsal',
    locationPlz: '76646',
    distanceKm: 18,
    postedDate: 'Gestern, 19:30',
    condition: 'Wie neu',
    descriptionDe: 'Samsung QLED 4K Smart-TV mit 65 Zoll Bildschirmdiagonale (163 cm). Sehr schnelles Tizen OS mit allen gängigen Streaming-Apps. Inklusive Solar-Fernbedienung und Wandhalterung.',
    descriptionEn: 'Samsung QLED 4K Smart TV with 65-inch screen. Smooth Tizen OS with all streaming apps. Includes Solar Smart remote and wall mount bracket.',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 156,
    favoriteCount: 17,
    seller: DEMO_SELLERS.sophie,
  },
  {
    id: 'demo-10',
    isDemo: true,
    slug: 'gaming-pc-rtx-4070-ryzen-7-stuttgart',
    title: 'Gaming-PC RTX 4070, Ryzen 7',
    categorySlug: 'elektronik',
    categoryNameDe: 'Technik & Elektronik',
    categoryNameEn: 'Tech & Electronics',
    subcategory: 'PCs & Laptops',
    price: 1290,
    previousPrice: 1350,
    priceType: 'fixed',
    locationCity: 'Stuttgart',
    locationPlz: '70174',
    distanceKm: 48,
    postedDate: 'Vor 2 Tagen',
    condition: 'Wie neu',
    descriptionDe: 'Leistungsstarker Gaming-Rechner mit Nvidia GeForce RTX 4070, AMD Ryzen 7 7700X, 32 GB DDR5 RAM und 2 TB NVMe SSD. Läuft leise und bewältigt moderne Spiele in 1440p/4K.',
    descriptionEn: 'High-performance gaming PC featuring Nvidia RTX 4070, AMD Ryzen 7 7700X, 32 GB DDR5 RAM, and 2 TB NVMe SSD. Quiet operation for 1440p and 4K gaming.',
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80'],
    hasVideo: true,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hand-holding-a-smartphone-with-green-screen-41544-large.mp4',
    deliveryOptions: 'Abholung & Versicherter Versand',
    shippingAvailable: true,
    views: 320,
    favoriteCount: 45,
    seller: DEMO_SELLERS.daniel,
  },

  // --- Haus & Garten ---
  {
    id: 'demo-11',
    isDemo: true,
    slug: 'massivholz-esstisch-mit-sechs-stuehlen-rastatt',
    title: 'Massivholz-Esstisch mit sechs Stühlen',
    categorySlug: 'haus-garten',
    categoryNameDe: 'Haus & Garten',
    categoryNameEn: 'Home & Garden',
    subcategory: 'Möbel & Einrichtung',
    price: 480,
    priceType: 'negotiable',
    locationCity: 'Rastatt',
    locationPlz: '76437',
    distanceKm: 15,
    postedDate: 'Heute, 08:30',
    condition: 'Gebraucht',
    descriptionDe: 'Hochwertiger Esstisch aus geölter Eiche (Maße 180 x 90 cm) zusammen mit sechs passenden Polsterstühlen in Anthrazit. Sehr stabiler Zustand mit leichten Gebrauchsspuren.',
    descriptionEn: 'High-quality oiled oak dining table (180 x 90 cm) with six matching upholstered chairs in charcoal grey. Solid construction with minor signs of wear.',
    images: ['https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 110,
    favoriteCount: 14,
    seller: DEMO_SELLERS.laura,
  },
  {
    id: 'demo-12',
    isDemo: true,
    slug: 'weber-gasgrill-spirit-ii-baden-baden',
    title: 'Weber Gasgrill Spirit II',
    categorySlug: 'haus-garten',
    categoryNameDe: 'Haus & Garten',
    categoryNameEn: 'Home & Garden',
    subcategory: 'Garten & Pflanzen',
    price: 310,
    priceType: 'fixed',
    locationCity: 'Baden-Baden',
    locationPlz: '76530',
    distanceKm: 28,
    postedDate: 'Gestern, 15:20',
    condition: 'Gebraucht',
    descriptionDe: 'Weber Spirit II E-310 GBS Gasgrill mit drei Edelstahlbrennern und Gusseisenrost. Regelmäßig gereinigt und stets mit Abdeckhaube auf der überdachten Terrasse geschützt.',
    descriptionEn: 'Weber Spirit II E-310 GBS gas grill with three stainless steel burners and cast iron grate. Cleaned regularly and kept protected with cover under roof.',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 175,
    favoriteCount: 23,
    seller: DEMO_SELLERS.markus,
  },
  {
    id: 'demo-13',
    isDemo: true,
    slug: 'bosch-akku-rasenmaeher-ettlingen',
    title: 'Bosch Akku-Rasenmäher',
    categorySlug: 'haus-garten',
    categoryNameDe: 'Haus & Garten',
    categoryNameEn: 'Home & Garden',
    subcategory: 'Heimwerker & Werkzeug',
    price: 190,
    priceType: 'negotiable',
    locationCity: 'Ettlingen',
    locationPlz: '76275',
    distanceKm: 7,
    postedDate: 'Vor 2 Tagen',
    condition: 'Wie neu',
    descriptionDe: 'Bosch CityMower 18V Akku-Rasenmäher inklusive zwei 4.0 Ah Akkus und Schnellladegerät. Ideal für Rasenflächen bis 300 m². Nur eine Saison verwendet.',
    descriptionEn: 'Bosch CityMower 18V cordless lawn mower with two 4.0 Ah batteries and fast charger. Perfect for lawns up to 300 m². Used for only one season.',
    images: ['https://images.unsplash.com/photo-1592417817098-8f3d6ef23a8d?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Abholung bevorzugt',
    shippingAvailable: true,
    views: 89,
    favoriteCount: 11,
    seller: DEMO_SELLERS.hausGarten,
  },

  // --- Mode & Accessoires ---
  {
    id: 'demo-14',
    isDemo: true,
    slug: 'herren-lederjacke-groesse-l-karlsruhe',
    title: 'Herren-Lederjacke, Größe L',
    categorySlug: 'mode-beauty',
    categoryNameDe: 'Mode & Accessoires',
    categoryNameEn: 'Fashion & Accessories',
    subcategory: 'Herrenbekleidung',
    price: 85,
    priceType: 'negotiable',
    locationCity: 'Karlsruhe',
    locationPlz: '76133',
    distanceKm: 2,
    postedDate: 'Heute, 13:10',
    condition: 'Gebraucht',
    descriptionDe: 'Echtleder-Bikerjacke für Herren in dunklem Braun. Weiches Lammleder mit schöner Patina und Reißverschlüssen an den Ärmeln. Passform regulär L.',
    descriptionEn: 'Men real leather biker jacket in dark brown. Soft lambskin leather with natural patina and zipper details on sleeves. Regular size L fit.',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Versand möglich (5 €)',
    shippingAvailable: true,
    views: 65,
    favoriteCount: 8,
    seller: DEMO_SELLERS.jonas,
  },
  {
    id: 'demo-15',
    isDemo: true,
    slug: 'designer-handtasche-aus-leder-mannheim',
    title: 'Designer-Handtasche aus Leder',
    categorySlug: 'mode-beauty',
    categoryNameDe: 'Mode & Accessoires',
    categoryNameEn: 'Fashion & Accessories',
    subcategory: 'Taschen & Accessoires',
    price: 240,
    priceType: 'fixed',
    locationCity: 'Mannheim',
    locationPlz: '68161',
    distanceKm: 32,
    postedDate: 'Gestern, 11:00',
    condition: 'Wie neu',
    descriptionDe: 'Elegante Schultertasche aus feinem Kalbsleder in Nude/Beige. Innenfutter saubere Baumwolle, inklusive Staubbeutel und Echtheitszertifikat.',
    descriptionEn: 'Elegant shoulder bag crafted from fine calfskin leather in nude/beige. Clean cotton lining, comes with dustbag and certificate of authenticity.',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Versicherter Versand inklusive',
    shippingAvailable: true,
    views: 140,
    favoriteCount: 26,
    seller: DEMO_SELLERS.elena,
  },
  {
    id: 'demo-16',
    isDemo: true,
    slug: 'nike-sneaker-ungetragen-groesse-43-pforzheim',
    title: 'Nike Sneaker, ungetragen, Größe 43',
    categorySlug: 'mode-beauty',
    categoryNameDe: 'Mode & Accessoires',
    categoryNameEn: 'Fashion & Accessories',
    subcategory: 'Schuhe',
    price: 95,
    previousPrice: 120,
    priceType: 'fixed',
    locationCity: 'Pforzheim',
    locationPlz: '75175',
    distanceKm: 25,
    postedDate: 'Vor 3 Tagen',
    condition: 'Neu',
    descriptionDe: 'Nike Air Max 1 in der Farbkombination Weiß/Grau/Grün. Absolut neu und ungetragen im Originalkarton. Größe US 9.5 / EU 43.',
    descriptionEn: 'Nike Air Max 1 in White/Grey/Green colorway. Brand new and unworn in original box. Size US 9.5 / EU 43.',
    images: ['https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Abholung oder DHL Paket',
    shippingAvailable: true,
    views: 112,
    favoriteCount: 15,
    seller: DEMO_SELLERS.daniel,
  },

  // --- Baby, Kind & Familie ---
  {
    id: 'demo-17',
    isDemo: true,
    slug: 'bugaboo-kinderwagen-mit-zubehoer-karlsruhe',
    title: 'Bugaboo Kinderwagen mit Zubehör',
    categorySlug: 'baby-kind',
    categoryNameDe: 'Baby, Kind & Familie',
    categoryNameEn: 'Baby, Kids & Family',
    subcategory: 'Kinderwagen & Sitze',
    price: 420,
    priceType: 'negotiable',
    locationCity: 'Karlsruhe',
    locationPlz: '76135',
    distanceKm: 4,
    postedDate: 'Heute, 10:00',
    condition: 'Gebraucht',
    descriptionDe: 'Bugaboo Fox Kombination aus Babywanne und Sportsitz. Inklusive Regenverdeck, Sonnendach, Lammfellsack und Adaptern für die Babyschale.',
    descriptionEn: 'Bugaboo Fox combo featuring bassinet and toddler seat. Includes rain cover, sun canopy, fleece footmuff, and car seat adapters.',
    images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 130,
    favoriteCount: 19,
    seller: DEMO_SELLERS.sophie,
  },
  {
    id: 'demo-18',
    isDemo: true,
    slug: 'kinderfahrrad-20-zoll-bruchsal',
    title: 'Kinderfahrrad 20 Zoll',
    categorySlug: 'baby-kind',
    categoryNameDe: 'Baby, Kind & Familie',
    categoryNameEn: 'Baby, Kids & Family',
    subcategory: 'Spielzeug & Sport',
    price: 110,
    priceType: 'fixed',
    locationCity: 'Bruchsal',
    locationPlz: '76646',
    distanceKm: 19,
    postedDate: 'Gestern, 17:00',
    condition: 'Gebraucht',
    descriptionDe: 'Leichtes 20 Zoll Kinderfahrrad von Puky mit 3-Gang Shimano Nabenschaltung, Rücktrittbremse und funktionierender Beleuchtung mit Nabendynamo.',
    descriptionEn: 'Lightweight 20-inch kids bike by Puky with 3-speed Shimano hub gear, coaster brake, and working Dynamo LED lights.',
    images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 74,
    favoriteCount: 10,
    seller: DEMO_SELLERS.markus,
  },
  {
    id: 'demo-19',
    isDemo: true,
    slug: 'komplettes-babyzimmer-in-weiss-heidelberg',
    title: 'Komplettes Babyzimmer in Weiß',
    categorySlug: 'baby-kind',
    categoryNameDe: 'Baby, Kind & Familie',
    categoryNameEn: 'Baby, Kids & Family',
    subcategory: 'Kindermöbel',
    price: 350,
    priceType: 'negotiable',
    locationCity: 'Heidelberg',
    locationPlz: '69120',
    distanceKm: 28,
    postedDate: 'Vor 4 Tagen',
    condition: 'Wie neu',
    descriptionDe: 'Dreiteiliges Babyzimmer bestehend aus umbaubarem Gitterbett (70x140 cm), Wickelkommode mit abnehmbarem Aufsatz und zweitürigem Kleiderschrank.',
    descriptionEn: 'Three-piece nursery set featuring convertible cot bed (70x140 cm), changing dresser with removable top, and two-door wardrobe.',
    images: ['https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Selbstabbau & Abholung',
    shippingAvailable: false,
    views: 205,
    favoriteCount: 29,
    seller: DEMO_SELLERS.laura,
  },

  // --- Jobs & Dienstleistungen ---
  {
    id: 'demo-20',
    isDemo: true,
    slug: 'professionelle-fensterreinigung-karlsruhe',
    title: 'Professionelle Fensterreinigung',
    categorySlug: 'jobs-karriere',
    categoryNameDe: 'Jobs & Dienstleistungen',
    categoryNameEn: 'Jobs & Services',
    subcategory: 'Handwerker & Umzug',
    price: 49,
    priceType: 'fixed',
    locationCity: 'Karlsruhe',
    locationPlz: '76133',
    distanceKm: 1,
    postedDate: 'Heute, 09:00',
    condition: 'Neu',
    descriptionDe: 'Zuverlässige streifenfreie Fenster- und Rahmenreinigung für Wohnungen, Häuser und Büros in Karlsruhe. Transparenter Pauschalpreis ab 49 €.',
    descriptionEn: 'Reliable streak-free window and frame cleaning service for flats, houses, and offices in Karlsruhe area. Clear flat prices starting at 49 €.',
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Vor-Ort Service',
    shippingAvailable: false,
    views: 160,
    favoriteCount: 15,
    seller: DEMO_SELLERS.hausGarten,
  },
  {
    id: 'demo-21',
    isDemo: true,
    slug: 'gartenpflege-und-heckenschnitt-ettlingen',
    title: 'Gartenpflege und Heckenschnitt',
    categorySlug: 'jobs-karriere',
    categoryNameDe: 'Jobs & Dienstleistungen',
    categoryNameEn: 'Jobs & Services',
    subcategory: 'Handwerker & Umzug',
    price: 35,
    priceType: 'fixed',
    locationCity: 'Ettlingen',
    locationPlz: '76275',
    distanceKm: 8,
    postedDate: 'Gestern, 12:00',
    condition: 'Neu',
    descriptionDe: 'Erfahrenes Team übernimmt Heckenschnitt, Rasenmähen, Unkrautbeseitigung und Entsorgung von Grüngut. Stundenlohn 35 € pro Stunde.',
    descriptionEn: 'Experienced gardening team available for hedge trimming, lawn mowing, weed removal, and green waste disposal. Hourly rate 35 € per hour.',
    images: ['https://images.unsplash.com/photo-1558904541-efa8c196b27d?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Vor-Ort Service',
    shippingAvailable: false,
    views: 118,
    favoriteCount: 14,
    seller: DEMO_SELLERS.hausGarten,
  },
  {
    id: 'demo-22',
    isDemo: true,
    slug: 'umzugshilfe-mit-transporter-mannheim',
    title: 'Umzugshilfe mit Transporter',
    categorySlug: 'jobs-karriere',
    categoryNameDe: 'Jobs & Dienstleistungen',
    categoryNameEn: 'Jobs & Services',
    subcategory: 'Handwerker & Umzug',
    price: 35,
    priceType: 'fixed',
    locationCity: 'Mannheim',
    locationPlz: '68159',
    distanceKm: 30,
    postedDate: 'Vor 2 Tagen',
    condition: 'Neu',
    descriptionDe: 'Kompetente Umzugshelfer inklusive geräumigem Transporter (3.5t) für Möbeltransporte, Entrümpelungen und Kleinumzüge. Stundensatz 35 € pro Stunde.',
    descriptionEn: 'Efficient moving helpers including spacious 3.5t van for furniture transport and home relocations. Hourly rate from 35 € per hour.',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Vor-Ort Service',
    shippingAvailable: false,
    views: 215,
    favoriteCount: 28,
    seller: DEMO_SELLERS.markus,
  },

  // --- Haustiere & Zubehör ---
  {
    id: 'demo-23',
    isDemo: true,
    slug: 'grosser-kratzbaum-sehr-guter-zustand-karlsruhe',
    title: 'Großer Kratzbaum, sehr guter Zustand',
    categorySlug: 'haustiere',
    categoryNameDe: 'Haustiere & Zubehör',
    categoryNameEn: 'Pets & Supplies',
    subcategory: 'Zubehör & Futter',
    price: 70,
    priceType: 'negotiable',
    locationCity: 'Karlsruhe',
    locationPlz: '76137',
    distanceKm: 3,
    postedDate: 'Heute, 15:00',
    condition: 'Wie neu',
    descriptionDe: 'Stabiler Deckenkratzbaum (Höhe verstellbar von 230 bis 260 cm) mit dicken Sisalsäulen, zwei Kuschelhöhlen und Hängematten. Sehr gut erhalten.',
    descriptionEn: 'Sturdy floor-to-ceiling cat tree (adjustable height 230-260 cm) with thick sisal posts, two cozy dens, and hammocks. Great condition.',
    images: ['https://images.unsplash.com/photo-1545249390-6bdfa286032f?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 92,
    favoriteCount: 13,
    seller: DEMO_SELLERS.sophie,
  },
  {
    id: 'demo-24',
    isDemo: true,
    slug: 'hundetransportbox-fuer-das-auto-rastatt',
    title: 'Hundetransportbox für das Auto',
    categorySlug: 'haustiere',
    categoryNameDe: 'Haustiere & Zubehör',
    categoryNameEn: 'Pets & Supplies',
    subcategory: 'Zubehör & Futter',
    price: 95,
    priceType: 'fixed',
    locationCity: 'Rastatt',
    locationPlz: '76437',
    distanceKm: 16,
    postedDate: 'Gestern, 14:00',
    condition: 'Gebraucht',
    descriptionDe: 'Aluminium-Hundetransportbox in Trapezform für den Kofferraum. Passend für mittelgroße bis große Hunde. Maße: Tiefe 80 cm, Breite 65 cm, Höhe 65 cm.',
    descriptionEn: 'Aluminium trapezoid dog travel crate for car trunk. Suitable for medium to large dogs. Dimensions: depth 80 cm, width 65 cm, height 65 cm.',
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80'],
    hasVideo: false,
    deliveryOptions: 'Nur Abholung',
    shippingAvailable: false,
    views: 104,
    favoriteCount: 16,
    seller: DEMO_SELLERS.daniel,
  },
];
